window.questions = [
  { id: 1, set: 1, text: "If we decided to take a spontaneous trip tomorrow, where would you want to go and why?" },
  { id: 2, set: 1, text: "What is a small thing that made you smile recently?" },
  { id: 3, set: 1, text: "What does your perfect calm day look like?" },
  { id: 4, set: 1, text: "What habit or routine would you like to improve?" },
  { id: 5, set: 1, text: "What do people often misunderstand about you?" },
  { id: 6, set: 1, text: "What is one small thing we could improve about our evenings together?" },
  { id: 7, set: 1, text: "Is there a movie, show, or genre you really want me to watch with you?" },
  { id: 8, set: 1, text: "What does an ideal Sunday look like for you?" },
  { id: 9, set: 1, text: "What is your favorite memory from the last year?" },
  { id: 10, set: 1, text: "When do you feel most like yourself?" },
  { id: 11, set: 1, text: "What is something you appreciate about me but don’t say often?" },
  { id: 12, set: 1, text: "If we had a shared inside joke in three words, what would it be?" },

  { id: 13, set: 2, text: "What does being a good partner mean to you in real life?" },
  { id: 14, set: 2, text: "When do you feel most loved?" },
  { id: 15, set: 2, text: "How do you usually deal with conflict?" },
  { id: 16, set: 2, text: "What relationship lesson was hardest for you to learn?" },
  { id: 17, set: 2, text: "If we could set one rule for arguments, what should it be?" },
  { id: 18, set: 2, text: "What is one thing you wish I did more often?" },
  { id: 19, set: 2, text: "What is one thing you wish I did less often?" },
  { id: 20, set: 2, text: "What does trust mean to you?" },
  { id: 21, set: 2, text: "When do you feel most supported?" },
  { id: 22, set: 2, text: "What is a sign that you are stressed and need space or help?" },
  { id: 23, set: 2, text: "What makes you feel safe in a relationship?" },
  { id: 24, set: 2, text: "If we had a weekly ritual together, what would it be?" },

  { id: 25, set: 3, text: "What is something you want to achieve in the next year?" },
  { id: 26, set: 3, text: "What fear would you like to overcome, even a little?" },
  { id: 27, set: 3, text: "What is your emotional soft spot?" },
  { id: 28, set: 3, text: "When was the last time you felt truly proud of yourself?" },
  { id: 29, set: 3, text: "How do you imagine our future together in one sentence?" },
  { id: 30, set: 3, text: "What is a relationship deal-breaker for you?" },
  { id: 31, set: 3, text: "What do you think is your biggest weakness in communication?" },
  { id: 32, set: 3, text: "What should I understand better about you?" },
  { id: 33, set: 3, text: "What is something you have wanted to tell me but postponed?" },
  { id: 34, set: 3, text: "When do you feel closest to me?" },
  { id: 35, set: 3, text: "What do you hope we will know about each other in five years?" },
  { id: 36, set: 3, text: "Name three things you truly appreciate about us, and why." }
];
